// Realistic institutional mock dataset for seamless cloud demo fallback

export const defaultUsers = [
  {
    _id: "1",
    id: "1",
    name: "Dr. Suresh Sharma",
    email: "admin@edulead.edu",
    role: "ADMIN",
    phone: "+91 98201 11223",
    department: "Dean of Admissions",
    specialization: ["Strategy", "Policy"],
    isActive: true,
  },
  {
    _id: "2",
    id: "2",
    name: "Ananya Deshmukh",
    email: "manager@edulead.edu",
    role: "MANAGER",
    phone: "+91 98202 22334",
    department: "Admissions Operations",
    specialization: ["Lead Operations"],
    isActive: true,
  },
  {
    _id: "3",
    id: "3",
    name: "Priya Nair",
    email: "priya@edulead.edu",
    role: "COUNSELLOR",
    phone: "+91 98203 33445",
    department: "UG Admissions",
    specialization: ["BCA", "BBA", "B.Com"],
    isActive: true,
  },
  {
    _id: "4",
    id: "4",
    name: "Rohan Verma",
    email: "rohan@edulead.edu",
    role: "COUNSELLOR",
    phone: "+91 98204 44556",
    department: "Engineering Admissions",
    specialization: ["B.Tech CSE", "AI", "MCA"],
    isActive: true,
  },
];

export const defaultLeads = [
  {
    _id: "101",
    id: "101",
    leadId: "LED-2026-1001",
    studentName: "Rahul Kumar",
    phone: "+91 98450 12345",
    email: "rahul.kumar@gmail.com",
    coursePreference: "BCA",
    source: "WhatsApp",
    status: "INTERESTED",
    priority: "HIGH",
    assignedCounsellor: defaultUsers[2],
    city: "Bangalore",
    previousEducation: "12th Science",
    percentage: "84.5%",
    ageInDays: 4,
    notes: "Interested in BCA with Cloud Specialization. Asked about hostel and installment facility.",
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    lastContactDate: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    _id: "102",
    id: "102",
    leadId: "LED-2026-1002",
    studentName: "Anita Rao",
    phone: "+91 98450 23456",
    email: "anita.rao@outlook.com",
    coursePreference: "B.Tech CSE",
    source: "Website",
    status: "APPLICATION",
    priority: "URGENT",
    assignedCounsellor: defaultUsers[3],
    city: "Hyderabad",
    previousEducation: "12th CBSE",
    percentage: "91.2%",
    ageInDays: 8,
    notes: "Application form submitted online. Verification of 12th marksheet in progress.",
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    lastContactDate: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    _id: "103",
    id: "103",
    leadId: "LED-2026-1003",
    studentName: "Vikram Malhotra",
    phone: "+91 98450 34567",
    email: "vikram.m@gmail.com",
    coursePreference: "MBA",
    source: "Walk-in",
    status: "CONVERTED",
    priority: "HIGH",
    assignedCounsellor: defaultUsers[1],
    city: "Mumbai",
    previousEducation: "B.Com (Hons)",
    percentage: "78.0%",
    ageInDays: 14,
    notes: "Admitted into MBA Finance. Scholarship fee waiver approved.",
    conversionDetails: {
      admissionId: "ADM-2026-MBA-089",
      feePaid: 75000,
      receiptNumber: "REC-2026-4491",
      enrolledAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      remarks: "First installment paid online via NEFT.",
    },
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    _id: "104",
    id: "104",
    leadId: "LED-2026-1004",
    studentName: "Sneha Patel",
    phone: "+91 98450 45678",
    email: "sneha.patel@yahoo.com",
    coursePreference: "B.Tech AI",
    source: "Fair",
    status: "FOLLOW_UP",
    priority: "MEDIUM",
    assignedCounsellor: defaultUsers[3],
    city: "Ahmedabad",
    previousEducation: "12th GSEB",
    percentage: "86.4%",
    ageInDays: 6,
    notes: "Met at Education Expo. Requested syllabus comparison with traditional CSE.",
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    _id: "105",
    id: "105",
    leadId: "LED-2026-1005",
    studentName: "Kiran Joshi",
    phone: "+91 98450 56789",
    email: "kiran.joshi@gmail.com",
    coursePreference: "BBA",
    source: "Phone",
    status: "NEW",
    priority: "MEDIUM",
    assignedCounsellor: null, // Unassigned pool
    city: "Pune",
    previousEducation: "12th Commerce",
    percentage: "76.2%",
    ageInDays: 1,
    notes: "Inquired about fee structure and sports quota eligibility.",
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    _id: "106",
    id: "106",
    leadId: "LED-2026-1006",
    studentName: "Amit Verma",
    phone: "+91 98450 67890",
    email: "amit.verma@hotmail.com",
    coursePreference: "MCA",
    source: "Campaign",
    status: "CONTACTED",
    priority: "LOW",
    assignedCounsellor: defaultUsers[2],
    city: "Delhi NCR",
    previousEducation: "B.Sc Computer Science",
    percentage: "72.0%",
    ageInDays: 3,
    notes: "Working professional looking for evening/weekend options.",
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    _id: "107",
    id: "107",
    leadId: "LED-2026-1007",
    studentName: "Pooja Gupta",
    phone: "+91 98450 78901",
    email: "pooja.gupta@gmail.com",
    coursePreference: "BCA",
    source: "Website",
    status: "LOST",
    priority: "LOW",
    assignedCounsellor: defaultUsers[2],
    city: "Jaipur",
    previousEducation: "12th Science",
    percentage: "68.5%",
    ageInDays: 18,
    lostReason: "Budget / High Fee Structure",
    lostNotes: "Parents opted for local state college to avoid hostel charges.",
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    _id: "108",
    id: "108",
    leadId: "LED-2026-1008",
    studentName: "Arjun Singh",
    phone: "+91 98450 89012",
    email: "arjun.singh@gmail.com",
    coursePreference: "B.Tech CSE",
    source: "WhatsApp",
    status: "FOLLOW_UP",
    priority: "HIGH",
    assignedCounsellor: defaultUsers[3],
    city: "Chandigarh",
    previousEducation: "12th CBSE",
    percentage: "89.5%",
    ageInDays: 16,
    notes: "Awaiting JEE Main Round 2 results before confirming admission.",
    createdAt: new Date(Date.now() - 16 * 86400000).toISOString(),
  }
];

export const defaultFollowups = [
  {
    _id: "201",
    id: "201",
    leadId: defaultLeads[0],
    counsellorId: defaultUsers[2],
    scheduledDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    scheduledTime: "11:30 AM",
    type: "Phone Call",
    status: "COMPLETED",
    notes: "Explained course curriculum and fee structure.",
    nextAction: "Send brochure and hostel fee sheet via WhatsApp.",
    completedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    _id: "202",
    id: "202",
    leadId: defaultLeads[7], // Arjun Singh
    counsellorId: defaultUsers[3],
    scheduledDate: new Date(Date.now() - 2 * 86400000).toISOString(), // Overdue
    scheduledTime: "02:30 PM",
    type: "Phone Call",
    status: "PENDING",
    notes: "Follow-up on JEE rank status.",
    nextAction: "Call student and check counseling round",
  },
  {
    _id: "203",
    id: "203",
    leadId: defaultLeads[0], // Rahul Kumar
    counsellorId: defaultUsers[2],
    scheduledDate: new Date(Date.now() + 1 * 86400000).toISOString(),
    scheduledTime: "11:00 AM",
    type: "WhatsApp",
    status: "PENDING",
    notes: "Share scholarship and fee concessions.",
    nextAction: "Confirm parent visit",
  }
];

export const defaultDashboard = {
  metrics: {
    totalLeads: 15,
    newLeads: 4,
    followups: 3,
    converted: 4,
    lost: 2,
    overdue: 1,
    conversionRate: "26.7",
  },
  pipeline: [
    { stage: "NEW", count: 4 },
    { stage: "CONTACTED", count: 2 },
    { stage: "FOLLOW_UP", count: 3 },
    { stage: "INTERESTED", count: 3 },
    { stage: "APPLICATION", count: 2 },
    { stage: "CONVERTED", count: 4 },
  ],
  sources: [
    { source: "Website", total: 4, converted: 2, conversionRate: 50 },
    { source: "WhatsApp", total: 3, converted: 1, conversionRate: 33 },
    { source: "Walk-in", total: 2, converted: 1, conversionRate: 50 },
    { source: "Phone", total: 2, converted: 0, conversionRate: 0 },
    { source: "Fair", total: 2, converted: 1, conversionRate: 50 },
    { source: "Campaign", total: 2, converted: 0, conversionRate: 0 },
    { source: "Other", total: 1, converted: 0, conversionRate: 0 },
  ],
  ageing: [
    { range: "0–2 days", label: "Fresh", count: 5, color: "#10b981" },
    { range: "3–7 days", label: "Active", count: 4, color: "#3b82f6" },
    { range: "8–15 days", label: "At Risk", count: 3, color: "#f59e0b" },
    { range: "15+ days", label: "Stagnant", count: 2, color: "#ef4444" },
  ],
  recentLeads: defaultLeads.slice(0, 6),
};

export const defaultReports = {
  sourcePerformance: [
    { source: "Website", total: 4, converted: 2, lost: 1, inProgress: 1, conversionRate: 50 },
    { source: "WhatsApp", total: 3, converted: 1, lost: 0, inProgress: 2, conversionRate: 33 },
    { source: "Walk-in", total: 2, converted: 1, lost: 0, inProgress: 1, conversionRate: 50 },
    { source: "Phone", total: 2, converted: 0, lost: 1, inProgress: 1, conversionRate: 0 },
    { source: "Fair", total: 2, converted: 1, lost: 0, inProgress: 1, conversionRate: 50 },
    { source: "Campaign", total: 2, converted: 0, lost: 0, inProgress: 2, conversionRate: 0 },
    { source: "Other", total: 1, converted: 0, lost: 0, inProgress: 1, conversionRate: 0 },
  ],
  counsellorPerformance: [
    { id: "3", name: "Priya Nair", email: "priya@edulead.edu", totalAssigned: 5, converted: 2, lost: 1, pendingFollowups: 2, completedFollowups: 2, conversionRate: 40 },
    { id: "4", name: "Rohan Verma", email: "rohan@edulead.edu", totalAssigned: 4, converted: 1, lost: 1, pendingFollowups: 1, completedFollowups: 1, conversionRate: 25 },
    { id: "2", name: "Ananya Deshmukh", email: "manager@edulead.edu", totalAssigned: 2, converted: 1, lost: 0, pendingFollowups: 0, completedFollowups: 1, conversionRate: 50 },
  ],
  statusDistribution: [
    { status: "NEW", count: 4, percentage: 27 },
    { status: "CONTACTED", count: 2, percentage: 13 },
    { status: "FOLLOW_UP", count: 3, percentage: 20 },
    { status: "INTERESTED", count: 3, percentage: 20 },
    { status: "APPLICATION", count: 2, percentage: 13 },
    { status: "CONVERTED", count: 4, percentage: 27 },
    { status: "LOST", count: 2, percentage: 13 },
  ],
  ageingReport: [
    { _id: "108", leadId: "LED-2026-1008", studentName: "Arjun Singh", phone: "+91 98450 89012", coursePreference: "B.Tech CSE", source: "WhatsApp", status: "FOLLOW_UP", counsellorName: "Rohan Verma", ageDays: 16, lastContactDays: 8, riskCategory: "Critical" },
    { _id: "102", leadId: "LED-2026-1002", studentName: "Anita Rao", phone: "+91 98450 23456", coursePreference: "B.Tech CSE", source: "Website", status: "APPLICATION", counsellorName: "Rohan Verma", ageDays: 8, lastContactDays: 2, riskCategory: "Warning" },
    { _id: "101", leadId: "LED-2026-1001", studentName: "Rahul Kumar", phone: "+91 98450 12345", coursePreference: "BCA", source: "WhatsApp", status: "INTERESTED", counsellorName: "Priya Nair", ageDays: 4, lastContactDays: 1, riskCategory: "Normal" },
  ]
};
